name: cached_video_player_plus
description: "The video_player plugin that went to therapy, worked on its commitment issues, and now actually remembers your videos!"
version: 4.0.4
homepage: https://outdatedguy.rocks
repository: https://github.com/OutdatedGuy/cached_video_player_plus
topics:
  - caching
  - video-caching
  - video
  - video-player
funding:
  - https://coff.ee/outdatedguy
  - https://github.com/sponsors/OutdatedGuy
screenshots:
  - description: "A sleek, futuristic video player, designed for seamless streaming and robust caching performance. Experience cutting-edge visuals and uninterrupted playback."
    path: screenshots/thumbnail.png
  - description: "Example of Basic Video Playback on Android."
    path: screenshots/Android-Basic-Playback.webp
  - description: "Example of Chewie Integration on iOS."
    path: screenshots/iOS-Chewie-Integration.webp
  - description: "Example of Pre-Caching on macOS."
    path: screenshots/macOS-Pre-Caching.webp
  - description: "Example of Advance Cache Management on Windows."
    path: screenshots/Windows-Advance-Cache-Management.webp

environment:
  sdk: ^3.0.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.4.1
  get_storage: ^2.1.1

dev_dependencies:
  flutter_lints: ^5.0.0

dependency_overrides:
  shared_preferences:
    git:
      url: "https://gitcode.com/openharmony-tpc/flutter_packages.git"
      path: "packages/shared_preferences/shared_preferences"
      ref: "br_shared_preferences-v2.5.3_ohos"

  shared_preferences_android:
    git:
      url: "https://gitcode.com/openharmony-tpc/flutter_packages.git"
      path: "packages/shared_preferences/shared_preferences_android"
      ref: "br_shared_preferences-v2.5.3_ohos"

  shared_preferences_foundation:
    git:
      url: "https://gitcode.com/openharmony-tpc/flutter_packages.git"
      path: "packages/shared_preferences/shared_preferences_foundation"
      ref: "br_shared_preferences-v2.5.3_ohos"

  shared_preferences_platform_interface:
    git:
      url: "https://gitcode.com/openharmony-tpc/flutter_packages.git"
      path: "packages/shared_preferences/shared_preferences_platform_interface"
      ref: "br_shared_preferences-v2.5.3_ohos"

  shared_preferences_ohos:
    git:
      url: "https://gitcode.com/openharmony-tpc/flutter_packages.git"
      path: "packages/shared_preferences/shared_preferences_ohos"
      ref: "br_shared_preferences-v2.5.3_ohos"

  video_player:
    git:
      url: "https://gitcode.com/houtian87/flutter_packages.git"
      path: "packages/video_player/video_player"
      ref: "br_video_player-v2.10.0_ohos"


platforms:
  android:
  ios:
  macos:
  web:
  linux:
  windows:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
